# ── test environment ─────────────────────────────────────────
gcp_project_id  = "my-project-test"
gcp_region      = "us-central1"
tf_state_bucket = "my-tfstate-test"
project_name    = "myproject"

# ── Generation gmov6ip0c ──
gmov6ip0c_region = "us-west1"
gmov6ip0c_machine_type = "n2-highmem-8"
gmov6ip0c_image = "windows-cloud/windows-2022"
gmov6ip0c_disk_type = "pd-ssd"
gmov6ip0c_server_name = "GCPAPPTST03"
gmov6ip0c_project = "Name"
gmov6ip0c_additional_disks = "D:50,E:60"
gmov6ip0c_admin_email = "pchen@deloitte.com"
gmov6ip0c_admin_role = "Editor"
gmov6ip0c_machine_type_note = ""n2-highmem-4" has 4 vCPU / 32 GB RAM — does not meet your 4 vCPU / 46 GB requirement. Using higher in same family: n2-highmem-8 (8 vCPU / 64 GB RAM · High Memory)"
gmov6ip0c_ami_os = "Windows Server 2022"
gmov6ip0c_image_publisher = "MicrosoftWindowsServer"
gmov6ip0c_instance_type = "m5.xlarge"
gmov6ip0c_vm_size = "Standard_D4s_v3"
gmov6ip0c_user_email = "pchen@deloitte.com"
gmov6ip0c_role = "roles/editor"
gmov6ip0c_service_access = "COMPUTE"
gmov6ip0c_ram_gb = "46"
gmov6ip0c_cpu_cores = "4"